const KEY="flatplan-editorial-v4",LIBRARY_KEY="flatplan-publications-v1", $=s=>document.querySelector(s), esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const uid=()=>crypto.randomUUID(), sections=[{id:"front",name:"Front matter",color:"#eb6045"},{id:"story",name:"Our story",color:"#3451b2"},{id:"impact",name:"Impact",color:"#287c5a"},{id:"financial",name:"Financials",color:"#795aa6"},{id:"back",name:"Back matter",color:"#b76e10"}];
const milestoneDefs=[["firstDraft","First Draft Due"],["revision1","Revision Week 1"],["secondDraft","Second Draft Due"],["revision2","Revision Week 2"],["finalDraft","Final Draft Due"],["finalReview","Final Review"],["print","Send To Print Deadline"],["inHand","In Hand Deadline"],["presentation","Presentation Deadline"]];
const standardDefs=["Table of Contents","Managers List","Board of Directors","Financial Statements","Governance Index","Credits & Colophon","Contact Information","Legal Notices"];
const defaultReviewChecklist=[{id:"copy-final",label:"Copy is final and proofread"},{id:"assets-ready",label:"Images and graphics are approved for print"},{id:"layout-checked",label:"Layout, bleed, and folio are checked"},{id:"credits-verified",label:"Credits, captions, and data are verified"},{id:"final-approval",label:"Final page approval is recorded"}];
const seedStories=[["Chair’s letter","A candid reflection on the year’s turning points and the choices ahead.","approved","story","JB",1],["A year of momentum","The milestones that moved the strategy from intent to action.","approved","story","DK",4],["Our people in numbers","A compact data story on growth, mobility, and belonging.","approved","chart","AL",10],["Climate action","Progress against the transition plan, with proof points and next steps.","pitch","story","MS",null],["Community portrait","Full-bleed documentary image with a short first-person caption.","pitch","photo","SK",null],["Legacy systems advert","External placement submitted for review.","denied","ad","",null]];
const userData={title:"The Year in Perspective",sections:[{id:"front",name:"Front matter",color:"#eb6045"},{id:"story",name:"Our story",color:"#3451b2"},{id:"impact",name:"Impact",color:"#287c5a"},{id:"financial",name:"Financials",color:"#795aa6"},{id:"back",name:"Back matter",color:"#b76e10"}],pages:[{id:"p1",number:1,title:"",section:"front",layout:"visual"},{id:"p2",number:2,title:"",section:"front",layout:"standard"},{id:"p3",number:3,title:"",section:"front",layout:"standard"},{id:"p4",number:4,title:"",section:"front",layout:"standard"}],covers:[{id:"front-cover",title:"Front cover",layout:"visual"},{id:"inside-front",title:"Inside front cover",layout:"minimal"},{id:"inside-back",title:"Inside back cover",layout:"minimal"},{id:"back-cover",title:"Back cover",layout:"visual"}],stories:[{id:"0f49715c-83c1-4052-8ef9-ad8ff548909d",title:"Cover Photo",type:"photo",pitch:"",copy:"",status:"pitch",owner:"",pageId:""}],schedule:{firstDraft:"2027-02-05",revision1:"2027-02-08",secondDraft:"2027-02-19",revision2:"2027-02-22",finalDraft:"2027-02-26",finalReview:"2027-02-01",print:"2027-03-01",inHand:"2027-03-16",presentation:"2027-03-23"}};
function initial(){const data=structuredClone(userData);data.title="SHIFT REPORT Edition 2026";data.settings={accent:"#ff5a36",density:"compact",owners:[],finalReviewChecklist:structuredClone(defaultReviewChecklist)};return normalizePublication(data)}
function blankPublication(title){const data=initial();data.title=title;data.stories=[];Object.keys(data.schedule).forEach(key=>data.schedule[key]="");data.deadlines=milestoneDefs.map(([key,label])=>({id:key,kind:key,role:key==="finalDraft"?"finalDraft":"",name:label,dueDate:"",completedOn:"",createdOn:todayValue()}));return data}
let library=null,state=load(),view="spreads",workspaceMode="planning",storyFilter="unplaced",search="",dragStory="",desktopWriteQueue=Promise.resolve();
function normalizePublication(data){
  data=data&&typeof data==="object"?data:structuredClone(userData);
  data.title=String(data.title||"Untitled publication");
  data.sections=Array.isArray(data.sections)&&data.sections.length?data.sections:structuredClone(sections);
  data.pages=Array.isArray(data.pages)?data.pages:[];data.covers=Array.isArray(data.covers)?data.covers:structuredClone(userData.covers);data.stories=Array.isArray(data.stories)?data.stories:[];
  data.schedule=data.schedule&&typeof data.schedule==="object"?data.schedule:{};milestoneDefs.forEach(([key])=>data.schedule[key]??="");
  data.deadlineCompletions=data.deadlineCompletions&&typeof data.deadlineCompletions==="object"?data.deadlineCompletions:(data.scheduleCompleted||{});
  if(!Array.isArray(data.deadlines)||!data.deadlines.length)data.deadlines=milestoneDefs.map(([key,label],index)=>({id:key,kind:key,role:key==="finalDraft"?"finalDraft":"",name:label,dueDate:data.schedule[key]||"",completedOn:data.deadlineCompletions[key]||"",createdOn:data.scheduleCreatedOn||todayValue(),legacyIndex:index})).sort((a,b)=>{const aDate=localDate(a.dueDate),bDate=localDate(b.dueDate);return aDate&&bDate?aDate-bDate:aDate?-1:bDate?1:a.legacyIndex-b.legacyIndex});
  data.deadlines=data.deadlines.map((deadline,index)=>{const completedOn=String(deadline.completedOn||"");return{id:String(deadline.id||uid()),kind:deadline.kind||"custom",role:Object.prototype.hasOwnProperty.call(deadline,"role")?deadline.role:(deadline.kind==="finalDraft"||deadline.id==="finalDraft"?"finalDraft":""),name:String(deadline.name||`Deadline ${index+1}`),dueDate:String(deadline.dueDate||""),completedOn:/^\d{4}-\d{2}-\d{2}$/.test(completedOn)&&localDate(completedOn)?completedOn:"",createdOn:String(deadline.createdOn||todayValue()),owner:String(deadline.owner||""),notes:String(deadline.notes||"")}});
  let foundFinalDraft=false;data.deadlines.forEach(deadline=>{if(deadline.role!=="finalDraft")return;if(foundFinalDraft)deadline.role="";else foundFinalDraft=true});
  const savedSettings=data.settings&&typeof data.settings==="object"?data.settings:{};
  data.settings={accent:"#ff5a36",density:"compact",...savedSettings};
  const ownerSource=Array.isArray(savedSettings.owners)?savedSettings.owners:data.stories.flatMap(story=>Array.isArray(story.owners)?story.owners:[story.owner]);
  const seenOwners=new Set();data.settings.owners=ownerSource.map(owner=>String(owner||"").trim()).filter(owner=>{const key=owner.toLocaleLowerCase();if(!owner||seenOwners.has(key))return false;seenOwners.add(key);return true}).sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:"base"}));
  let checklist=data.settings.finalReviewChecklist||data.reviewChecklist;
  if(!Array.isArray(checklist)||!checklist.length)checklist=structuredClone(defaultReviewChecklist);
  data.settings.finalReviewChecklist=checklist.map((item,index)=>{const label=String(typeof item==="string"?item:item?.label||"").trim()||`Review item ${index+1}`;return{id:String(item?.id||`review-${index}-${label.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"item"}`),label,owner:String(item?.owner||"")}});
  data.pages.forEach((p,index)=>{p.id||=`p${index+1}`;p.number=index+1;p.title??="";p.section||="front";p.layout||="standard";p.reviewChecks=p.reviewChecks&&typeof p.reviewChecks==="object"?p.reviewChecks:{};p.assets=Array.isArray(p.assets)?p.assets:[]});
  data.covers.forEach((p,index)=>{p.id||=`cover-${index}`;p.title||=`Cover ${index+1}`;p.layout||="minimal";p.reviewChecks=p.reviewChecks&&typeof p.reviewChecks==="object"?p.reviewChecks:{};p.assets=Array.isArray(p.assets)?p.assets:[]});
  data.stories.forEach(x=>{x.id||=uid();x.title||="Untitled item";x.type||="standard";x.status||="planned";x.pitch??="";x.copy??="";x.owners=(Array.isArray(x.owners)?x.owners:[x.owner]).map(owner=>String(owner||"").trim()).filter((owner,index,list)=>owner&&list.findIndex(item=>item.toLocaleLowerCase()===owner.toLocaleLowerCase())===index);x.owner=x.owners[0]||"";x.completedOn=x.status==="complete"?String(x.completedOn||todayValue()):"";x.pageId??="";if(!["planned","approved","complete"].includes(x.status))x.pageId=""});data.activity=Array.isArray(data.activity)?data.activity:[];data.locked=Boolean(data.locked);data.lockedOn=String(data.lockedOn||"");data.template=String(data.template||"custom");
  return data;
}
function load(){try{const old=normalizePublication(JSON.parse(localStorage.getItem(KEY))||initial());if(old.title==="The Year in Perspective")old.title="SHIFT REPORT Edition 2026";const stored=JSON.parse(localStorage.getItem(LIBRARY_KEY));if(stored?.items?.length){library=stored;library.items.forEach(item=>item.data=normalizePublication(item.data));let item=library.items.find(x=>x.id===library.activeId&&!x.archived)||library.items.find(x=>!x.archived)||library.items[0];library.activeId=item.id;return item.data}library={activeId:uid(),items:[]};library.items.push({id:library.activeId,archived:false,updatedAt:new Date().toISOString(),data:old});localStorage.setItem(LIBRARY_KEY,JSON.stringify(library));return old}catch{const data=initial();library={activeId:uid(),items:[]};library.items.push({id:library.activeId,archived:false,updatedAt:new Date().toISOString(),data});return data}}
function syncLegacySchedule(data){data.deadlineCompletions={};milestoneDefs.forEach(([key])=>{const deadline=key==="finalDraft"?data.deadlines.find(item=>item.role==="finalDraft"):data.deadlines.find(item=>item.kind===key||item.id===key);data.schedule[key]=deadline?.dueDate||"";if(deadline?.completedOn)data.deadlineCompletions[key]=deadline.completedOn})}
function workspaceSnapshot(){return{format:"flatplan-workspace",version:1,savedAt:new Date().toISOString(),library:structuredClone(library)}}
function setFileStatus(text){const status=$("#fileStatus");if(status)status.textContent=text}
function updateFileStatus(filePath=""){setFileStatus(filePath?`Saved to ${filePath.split(/[\\/]/).pop()}`:window.flatplanDesktop?"Choose a project file to begin":"Saved in this browser")}
function queueDesktopSave(){if(!window.flatplanDesktop)return;const snapshot=workspaceSnapshot();setFileStatus("Saving…");desktopWriteQueue=desktopWriteQueue.then(()=>window.flatplanDesktop.autoSave(snapshot)).then(result=>{if(result?.conflict)setFileStatus("File changed elsewhere — choose Save");else if(result?.filePath)updateFileStatus(result.filePath);else if(result?.skipped)setFileStatus("Choose a project file to begin")}).catch(error=>{console.error("Flatplan auto-save failed",error);setFileStatus("Save failed — choose Save")})}
function save(autoSave=true){normalizePublication(state);syncLegacySchedule(state);let item=library.items.find(x=>x.id===library.activeId);if(!item){item={id:library.activeId,archived:false,data:state};library.items.push(item)}item.data=state;item.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(LIBRARY_KEY,JSON.stringify(library));if(autoSave)queueDesktopSave()}
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
function sec(id){return state.sections.find(x=>x.id===id)||state.sections[0]}function placed(pageId){return state.stories.filter(x=>x.pageId===pageId)}function storyOwners(item){return Array.isArray(item?.owners)?item.owners.filter(Boolean):item?.owner?[item.owner]:[]}function statusColor(s){return s==="complete"?"#176b45":s==="approved"?"#287c5a":s==="planned"?"#3451b2":s==="denied"?"#b42318":"#b76e10"}
function todayValue(){const now=new Date(),pad=n=>String(n).padStart(2,"0");return`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`}
function localDate(value){if(!value)return null;if(/^\d{4}-\d{2}-\d{2}$/.test(value))return new Date(`${value}T00:00:00`);const date=new Date(value);return Number.isNaN(date.getTime())?null:date}
function formatDate(value){const date=localDate(value);return date?date.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):""}
function previousDatedDeadline(index,list=state.deadlines){for(let cursor=index-1;cursor>=0;cursor--){if(localDate(list[cursor].dueDate))return list[cursor]}return null}
function reviewChecklist(){return state.settings.finalReviewChecklist}
function allProductionPages(){const byId=id=>state.covers.find(x=>x.id===id),ordered=[byId("front-cover"),byId("inside-front"),...state.pages,byId("inside-back"),byId("back-cover")].filter(Boolean),known=new Set(ordered.map(x=>x.id));return[...ordered,...state.covers.filter(x=>!known.has(x.id))]}
function reviewProgress(page){const checklist=reviewChecklist(),done=checklist.filter(item=>page.reviewChecks?.[item.id]).length;return{done,total:checklist.length,complete:checklist.length>0&&done===checklist.length}}
function clearPageReview(pageId){const page=state.pages.find(item=>item.id===pageId)||state.covers.find(item=>item.id===pageId);if(page)page.reviewChecks={}}
function clearPageReviews(...pageIds){new Set(pageIds.filter(Boolean)).forEach(clearPageReview)}
function finalDraftDeadline(){return state.deadlines.find(deadline=>deadline.role==="finalDraft")}
function finalReviewAvailable(){const finalDraft=finalDraftDeadline(),due=localDate(finalDraft?.dueDate),today=localDate(todayValue());return Boolean(finalDraft&&(finalDraft.completedOn||(due&&due<=today)))}
function getPrintReadiness(){
  const blockers=[],pageIds=new Set(allProductionPages().map(page=>page.id)),pitched=state.stories.filter(item=>item.status==="pitch"),incomplete=state.stories.filter(item=>["planned","approved"].includes(item.status)),unknown=state.stories.filter(item=>!["pitch","planned","approved","complete","denied"].includes(item.status)),unplaced=state.stories.filter(item=>["planned","approved","complete"].includes(item.status)&&!pageIds.has(item.pageId)),reviewPages=allProductionPages().filter(page=>!reviewProgress(page).complete);
  if(!state.pages.length||state.pages.length%4!==0)blockers.push("Interior page count must be a positive multiple of 4");
  if(pitched.length)blockers.push(`${pitched.length} pitched item${pitched.length===1?" needs":"s need"} a decision`);
  if(incomplete.length)blockers.push(`${incomplete.length} content item${incomplete.length===1?" needs":"s need"} to be marked complete`);
  if(unknown.length)blockers.push(`${unknown.length} item${unknown.length===1?" has":"s have"} an unresolved status`);
  if(unplaced.length)blockers.push(`${unplaced.length} approved or planned item${unplaced.length===1?" needs":"s need"} placement`);
  const finalDraft=finalDraftDeadline(),finalDraftIndex=finalDraft?state.deadlines.indexOf(finalDraft):-1,finalSequence=finalDraftIndex>=0?state.deadlines.slice(0,finalDraftIndex+1):[],openFinalDeadlines=finalSequence.filter(deadline=>!deadline.completedOn),sequenceConflict=finalSequence.some((deadline,index)=>{const previous=previousDatedDeadline(index,finalSequence),due=localDate(deadline.dueDate),previousDue=localDate(previous?.dueDate),completed=localDate(deadline.completedOn),previousCompleted=index?localDate(finalSequence[index-1].completedOn):null;return Boolean((deadline.completedOn&&!due)||(due&&previousDue&&due<previousDue)||(index&&deadline.completedOn&&!finalSequence[index-1].completedOn)||(completed&&previousCompleted&&completed<previousCompleted))});if(!finalDraft)blockers.push("Choose a final draft deadline");else if(openFinalDeadlines.length)blockers.push(`${openFinalDeadlines.length} production deadline${openFinalDeadlines.length===1?"":"s"} through ${finalDraft.name} need completion`);if(sequenceConflict)blockers.push("Production deadline sequence needs repair");
  if(reviewPages.length)blockers.push(`${reviewPages.length} page${reviewPages.length===1?" needs":"s need"} final review`);
  return{ready:blockers.length===0,blockers,pitched,incomplete,unknown,unplaced,reviewPages};
}
function render(){normalizePublication(state);document.documentElement.style.setProperty("--accent",state.settings.accent);document.documentElement.dataset.density=state.settings.density;const readiness=getPrintReadiness();$("#projectTitle").textContent=state.title;$("#interiorCount").textContent=state.pages.length;$("#placedCount").textContent=state.stories.filter(x=>x.pageId).length;$("#signatureText").textContent=readiness.ready?"Ready for print":`${readiness.blockers.length} print requirement${readiness.blockers.length===1?"":"s"} remaining`;$("#signatureDetail").textContent=readiness.ready?"Every idea is resolved and placed, the final-draft sequence is complete, and every page passed review.":readiness.blockers.join(" · ");$("#signatureBar").classList.toggle("invalid",!readiness.ready);$("#signatureMetric").classList.toggle("invalid",!readiness.ready);$("#signatureMetric").innerHTML=`<strong>${readiness.ready?"✓":"!"}</strong><span>${readiness.ready?"print ready":"not ready"}</span>`;$("#interiorLabel").textContent=view==="spreads"?`${state.pages.length/2+1} reader spreads · inside covers included`:`${state.pages.length+2} pages · inside covers included`;renderSchedule();renderStandardLibrary();renderStories();renderCovers();renderPages();window.renderSectionManager?.()}
function deadlineFill(deadline,index){if(deadline.completedOn)return 100;const due=localDate(deadline.dueDate),previous=previousDatedDeadline(index),start=localDate(previous?.completedOn||previous?.dueDate)||localDate(deadline.createdOn),today=localDate(todayValue());if(!due||!start)return 0;if(today>=due)return 100;if(due<=start)return 0;return Math.max(0,Math.min(100,(today-start)/(due-start)*100))}
function toggleDeadline(id){const index=state.deadlines.findIndex(deadline=>deadline.id===id),deadline=state.deadlines[index];if(!deadline)return;const laterComplete=state.deadlines.slice(index+1).some(item=>item.completedOn),priorComplete=state.deadlines.slice(0,index).every(item=>item.completedOn),due=localDate(deadline.dueDate),previousDue=localDate(previousDatedDeadline(index)?.dueDate);if(deadline.completedOn){if(laterComplete)return toast("Reopen later deadlines first");deadline.completedOn="";toast(`${deadline.name} reopened`)}else{if(!due)return toast("Set a due date before completing this deadline");if(previousDue&&due<previousDue)return toast("Fix the deadline order before completing this step");if(!priorComplete)return toast("Complete earlier deadlines first");deadline.completedOn=todayValue();toast(`${deadline.name} completed`)}save();render()}
function renderSchedule(){
  const today=localDate(todayValue()),firstIncomplete=state.deadlines.findIndex(deadline=>!deadline.completedOn);
  const openDeadlines=state.deadlines.filter(deadline=>!deadline.completedOn),nextDeadline=openDeadlines[0],nextDue=localDate(nextDeadline?.dueDate),nextDays=nextDue?Math.ceil((nextDue-today)/86400000):null,nextTiming=nextDays===null?"due date not set":nextDays<0?`${Math.abs(nextDays)} day${nextDays===-1?"":"s"} overdue`:nextDays===0?"due today":`${nextDays} day${nextDays===1?"":"s"} left`;$("#deadlineSummary").textContent=nextDeadline?`Next: ${nextDeadline.name} · ${nextTiming}`:"All deadlines complete";
  $("#deadlineBlocks").innerHTML=state.deadlines.length?state.deadlines.map((deadline,index)=>{const due=localDate(deadline.dueDate),previousDue=localDate(previousDatedDeadline(index)?.dueDate),dateConflict=Boolean(due&&previousDue&&due<previousDue),days=due?Math.ceil((due-today)/86400000):null,overdue=!deadline.completedOn&&days!==null&&days<0,priorComplete=state.deadlines.slice(0,index).every(item=>item.completedOn),laterComplete=state.deadlines.slice(index+1).some(item=>item.completedOn),canComplete=!deadline.completedOn&&priorComplete&&Boolean(due)&&!dateConflict,canReopen=Boolean(deadline.completedOn)&&!laterComplete,active=index===firstIncomplete,status=deadline.completedOn?`Completed ${formatDate(deadline.completedOn)}`:dateConflict?"Date is before prior step":!due?"Due date not set":overdue?`${Math.abs(days)} day${days===-1?"":"s"} overdue`:days===0?"Due today":`${days} day${days===1?"":"s"} left`,buttonLabel=deadline.completedOn?(canReopen?"Reopen":"Completed"):dateConflict?"Fix date order":canComplete?"Mark complete":priorComplete?"Set due date":"Waiting for prior deadline";return`<article class="deadline-block ${deadline.completedOn?"complete":dateConflict?"date-conflict":overdue?"overdue":active?"active":"locked"}"><span class="deadline-fill" style="width:${deadlineFill(deadline,index)}%"></span><div class="deadline-step">Step ${index+1}${deadline.role==="finalDraft"?" · Final draft":""}</div><h3>${esc(deadline.name)}</h3><time>${due?`Due ${formatDate(deadline.dueDate)}`:"No due date"}</time><strong>${status}</strong><button type="button" data-toggle-deadline="${esc(deadline.id)}" ${canComplete||canReopen?"":"disabled"}>${buttonLabel}</button></article>`}).join(""):`<div class="empty-deadlines"><strong>No deadlines yet.</strong><span>Use Edit deadlines to add the first production step.</span></div>`;
  $("#deadlineBlocks").querySelectorAll("[data-toggle-deadline]").forEach(button=>button.onclick=()=>toggleDeadline(button.dataset.toggleDeadline));
  $("#reviewPagesBtn").hidden=!finalReviewAvailable();
}
function renderStandardLibrary(){$("#standardLibrary").innerHTML=standardDefs.map(name=>`<button type="button" data-standard="${esc(name)}">＋ ${esc(name)}</button>`).join("");$("#standardLibrary").querySelectorAll("button").forEach(b=>b.onclick=()=>addStandard(b.dataset.standard))}
function addStandard(title){state.stories.unshift({id:uid(),title,pitch:"Standard publication element",copy:"",status:"planned",type:"standard",owners:[],owner:"",pageId:""});save();render();toast(`${title} added as planned`)}
function renderStories(){let xs=state.stories.filter(x=>storyFilter==="all"||(storyFilter==="unplaced"?!x.pageId:x.status===storyFilter)).filter(x=>(x.title+x.pitch+storyOwners(x).join(" ")).toLowerCase().includes(search));$("#storyList").innerHTML=xs.length?xs.map(x=>`<article class="story-card" data-id="${x.id}" draggable="${["approved","planned","complete"].includes(x.status)}" style="--status-color:${statusColor(x.status)}"><div class="story-top"><h3>${esc(x.title)}</h3><span class="type-badge">${esc(x.type)}</span></div><p>${esc(x.pitch||"No pitch added yet.")}</p><div class="story-foot"><span class="decision">${x.status}</span><span class="placed-on">${x.pageId?labelPage(x.pageId):storyOwners(x).join(", ")||"Unassigned"}</span></div></article>`).join(""):`<p class="empty-page">No items in this view.</p>`;document.querySelectorAll(".story-card").forEach(el=>{el.onclick=()=>openStory(el.dataset.id);el.ondragstart=e=>{dragStory=el.dataset.id;e.dataTransfer.setData("text/plain",dragStory)}})}
function pageHtml(p,isCover=false,isInside=false){const items=placed(p.id),section=(isCover||isInside)?{color:isInside?"#667085":"#111827",name:isInside?"Inside cover":"Cover"}:sec(p.section),review=reviewProgress(p);const pageMark=isCover?"COVER":isInside?"INSIDE":String(p.number).padStart(2,"0");return `<article class="page-card${isInside?" inside-cover":""}" data-page="${p.id}" style="border-top:4px solid ${section.color}" tabindex="0"><div class="page-meta"><b>${pageMark}</b><span>${isCover?"separate":esc(section.name)}</span></div><h3 class="page-title">${esc(p.title||"Untitled page")}</h3><div class="layout-canvas">${items.length?items.map(x=>`<div class="layout-block ${x.type}" title="${esc(x.title)}">${x.type==="story"?"":esc(x.title)}</div>`).join(""):`<div class="empty-page"><b>＋</b>Drop an item here</div>`}</div><div class="page-card-foot"><span class="page-count">${items.length} item${items.length===1?"":"s"}</span><span class="page-review-status ${review.complete?"complete":""}">${review.complete?"✓ ":""}${review.done}/${review.total} reviewed</span></div>${isCover?`<span class="cover-tag">${esc(p.title)}</span>`:""}</article>`}
function outsideCovers(){return state.covers.filter(x=>x.id==="front-cover"||x.id==="back-cover")}
function insideCover(id,title){return state.covers.find(x=>x.id===id)||{id,title,layout:"minimal"}}
function renderCovers(){$("#coverRail").innerHTML=outsideCovers().map(x=>pageHtml(x,true)).join("");bindPages($("#coverRail"))}
function spreadName(p){return p.number?String(p.number):p.id==="inside-front"?"inside front":"inside back"}
function renderPages(){const filtered=state.pages.filter(p=>(p.title+sec(p.section).name+placed(p.id).map(x=>x.title+storyOwners(x).join(" ")).join(" ")).toLowerCase().includes(search));const insideFront=insideCover("inside-front","Inside front cover"),insideBack=insideCover("inside-back","Inside back cover"),all=[insideFront,...filtered,insideBack];const el=$("#flatplan");el.classList.toggle("pages-mode",view==="pages");if(view==="pages")el.innerHTML=all.map(p=>pageHtml(p,false,!p.number)).join("");else{const groups=[];for(let i=0;i<all.length;i+=2)groups.push(all.slice(i,i+2));el.innerHTML=groups.map((g,i)=>`<div class="spread">${g.map(p=>pageHtml(p,false,!p.number)).join("")}<span class="spread-label">Spread ${i+1} · ${g.map(spreadName).join(" + ")}</span></div>`).join("")}bindPages(el)}
function bindPages(root){root.querySelectorAll(".page-card").forEach(el=>{el.onclick=()=>openPage(el.dataset.page);el.ondragover=e=>{e.preventDefault();el.classList.add("drop-target")};el.ondragleave=()=>el.classList.remove("drop-target");el.ondrop=e=>{e.preventDefault();e.stopPropagation();el.classList.remove("drop-target");placeStory(dragStory||e.dataTransfer.getData("text/plain"),el.dataset.page)}})}
function labelPage(id){const c=state.covers.find(x=>x.id===id);if(c)return c.title;const p=state.pages.find(x=>x.id===id);return p?`Page ${p.number}`:"Unplaced"}function allPageOptions(){return [...state.covers.map(x=>[x.id,x.title]),...state.pages.map(x=>[x.id,`Page ${x.number} · ${x.title}`])]}
function placeStory(id,pageId){const x=state.stories.find(s=>s.id===id);if(!x)return;if(!["approved","planned","complete"].includes(x.status)){toast("Approve, plan, or complete the item before placing it");return}if(x.pageId!==pageId){clearPageReviews(x.pageId,pageId);x.placedOn=""}x.pageId=pageId;save();render();toast(`${x.title} placed on ${labelPage(pageId)}`)}
function openStory(id="",presetPage="",presetType="story"){const x=state.stories.find(s=>s.id===id),selectedOwners=storyOwners(x),owners=[...state.settings.owners];selectedOwners.forEach(current=>{if(!owners.some(owner=>owner.toLocaleLowerCase()===current.toLocaleLowerCase()))owners.push(current)});$("#storyDialogTitle").textContent=x?"Edit editorial item":presetType==="story"?"Pitch a story":"Add an element";$("#storyId").value=x?.id||"";$("#storyTitle").value=x?.title||"";$("#storyType").value=x?.type||presetType;$("#storyPitch").value=x?.pitch||"";$("#storyCopy").value=x?.copy||"";$("#storyOwner").innerHTML=owners.map(owner=>`<option value="${esc(owner)}" ${selectedOwners.includes(owner)?"selected":""}>${esc(owner)}</option>`).join("");$("#storyStatus").value=x?.status||(presetType==="story"?"pitch":"planned");$("#storyPage").innerHTML=`<option value="">Unplaced</option>`+allPageOptions().map(([v,l])=>`<option value="${v}" ${(x?.pageId||presetPage)===v?"selected":""}>${esc(l)}</option>`).join("");$("#deleteStoryBtn").style.visibility=x?"visible":"hidden";$("#storyDialog").showModal()}
function openPage(id){
  const p=state.pages.find(x=>x.id===id)||state.covers.find(x=>x.id===id);if(!p)return;
  $("#pageDialogMode").textContent=workspaceMode==="design"?"DESIGN WORKSPACE":workspaceMode==="review"?"PAGE REVIEW":"PAGE PLAN";$("#pageDialog").dataset.mode=workspaceMode;
  $("#pageId").value=id;$("#pageDialogTitle").textContent=labelPage(id);$("#pageTitle").value=p.title;$("#pageLayout").value=p.layout||"standard";$("#pageSection").innerHTML=state.sections.map(s=>`<option value="${s.id}" ${p.section===s.id?"selected":""}>${esc(s.name)}</option>`).join("");$("#pageSection").disabled=!p.number;
  const items=placed(id);$("#placedItems").innerHTML=items.length?items.map(x=>`<div class="placed-row ${x.placedOn?"placement-confirmed":""}"><span><strong>${esc(x.title)}</strong><small>${esc(x.type)} · ${esc(x.status)}${x.placedOn?` · placed ${formatDate(x.placedOn)}`:" · placement pending"}</small></span><span class="placed-row-actions"><button class="placement-action" type="button" data-mark-placed="${x.id}" ${x.placedOn?"disabled":""}>${x.placedOn?"✓ Placed":"Mark placed"}</button><button type="button" data-edit-item="${x.id}">Edit</button><button type="button" data-remove="${x.id}">Remove</button></span></div>`).join(""):`<div class="placed-row"><span>No items placed yet</span></div>`;
  $("#placedItems").querySelectorAll("[data-edit-item]").forEach(b=>b.onclick=()=>openStory(b.dataset.editItem));
  $("#placedItems").querySelectorAll("[data-mark-placed]").forEach(b=>b.onclick=()=>{const story=state.stories.find(x=>x.id===b.dataset.markPlaced);if(!story)return;story.placedOn=todayValue();save();render();openPage(id);toast(`${story.title} marked placed`)});
  $("#placedItems").querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{const story=state.stories.find(x=>x.id===b.dataset.remove);if(!story)return;clearPageReview(id);story.pageId="";story.placedOn="";save();render();openPage(id)});
  const progress=reviewProgress(p);$("#pageReviewProgress").textContent=`${progress.done} / ${progress.total}`;$("#pageReviewProgress").classList.toggle("complete",progress.complete);$("#pageReviewHint").textContent=finalReviewAvailable()?"Final Draft is due. Complete every item before print ready.":"Required for print ready; review can be started before Final Draft is due.";
  $("#pageReviewChecklist").innerHTML=reviewChecklist().map(item=>`<label class="review-check"><input type="checkbox" data-review-item="${esc(item.id)}" ${p.reviewChecks[item.id]?"checked":""}><span>${esc(item.label)}</span>${p.reviewChecks[item.id]?`<small>Checked ${formatDate(p.reviewChecks[item.id])}</small>`:""}</label>`).join("");
  if(!$("#pageDialog").open){if(workspaceMode==="planning")$("#pageDialog").showModal();else $("#pageDialog").show()}
}
function renderReviewPageList(){const pages=allProductionPages();$("#reviewPageList").innerHTML=pages.map(page=>{const progress=reviewProgress(page);return`<div class="review-page-row ${progress.complete?"complete":""}"><div><strong>${esc(labelPage(page.id))}</strong><small>${esc(page.title||"Untitled page")}</small></div><span>${progress.complete?"Complete":`${progress.done} of ${progress.total}`}</span><button class="btn ${progress.complete?"light":"dark"}" type="button" data-review-page="${page.id}">${progress.complete?"Review":"Open checklist"}</button></div>`}).join("");$("#reviewPageList").querySelectorAll("[data-review-page]").forEach(button=>button.onclick=()=>{$("#reviewDialog").close();openPage(button.dataset.reviewPage)})}
function openFinalReview(){renderReviewPageList();$("#reviewDialog").showModal()}
$("#storyForm").onsubmit=e=>{e.preventDefault();const returnPage=$("#pageDialog").open?$("#pageId").value:"";let x=state.stories.find(s=>s.id===$("#storyId").value),previous=x?structuredClone(x):null;if(!x){x={id:uid()};state.stories.unshift(x)}const owners=[...$("#storyOwner").selectedOptions].map(option=>option.value),next={title:$("#storyTitle").value.trim(),type:$("#storyType").value,pitch:$("#storyPitch").value.trim(),copy:$("#storyCopy").value,status:$("#storyStatus").value,owners,owner:owners[0]||"",completedOn:$("#storyStatus").value==="complete"?(previous?.completedOn||todayValue()):"",pageId:$("#storyPage").value};if(!["approved","planned","complete"].includes(next.status))next.pageId="";const changed=!previous||["title","type","pitch","copy","status","pageId"].some(key=>previous[key]!==next[key])||JSON.stringify(storyOwners(previous))!==JSON.stringify(owners);if(changed)clearPageReviews(previous?.pageId,next.pageId);Object.assign(x,next);if(previous?.pageId!==next.pageId)x.placedOn="";if(next.status==="complete"&&previous?.status!=="complete")window.logActivity?.(`${next.title} marked complete`);save();$("#storyDialog").close();render();if(returnPage&&workspaceMode!=="planning")openPage(returnPage);toast(next.status==="complete"?"Editorial item completed":"Editorial item saved")};
$("#pageForm").onsubmit=e=>{e.preventDefault();const id=$("#pageId").value,p=state.pages.find(x=>x.id===id)||state.covers.find(x=>x.id===id),title=$("#pageTitle").value.trim(),layout=$("#pageLayout").value,section=p.number?$("#pageSection").value:p.section,planChanged=p.title!==title||p.layout!==layout||(p.number&&p.section!==section);p.title=title;p.layout=layout;if(p.number)p.section=section;if(planChanged)p.reviewChecks={};else $("#pageReviewChecklist").querySelectorAll("[data-review-item]").forEach(input=>{if(input.checked)p.reviewChecks[input.dataset.reviewItem]||=todayValue();else delete p.reviewChecks[input.dataset.reviewItem]});save();$("#pageDialog").close();render();toast(planChanged?"Page plan saved; final review reset":"Page plan and final review saved")};
document.querySelectorAll(".close-dialog").forEach(b=>b.onclick=()=>$("#storyDialog").close());document.querySelectorAll(".close-page").forEach(b=>b.onclick=()=>$("#pageDialog").close());document.querySelectorAll(".close-review").forEach(b=>b.onclick=()=>$("#reviewDialog").close());$("#reviewPagesBtn").onclick=openFinalReview;$("#deleteStoryBtn").onclick=()=>{const id=$("#storyId").value,story=state.stories.find(x=>x.id===id);clearPageReview(story?.pageId);state.stories=state.stories.filter(x=>x.id!==id);save();$("#storyDialog").close();render();toast("Item deleted")};
let deadlineEditorDraft=[];
function collectDeadlineEditor(){return[...$("#scheduleFields").querySelectorAll("[data-deadline-row]")].map(row=>({id:row.dataset.deadlineRow,kind:row.dataset.deadlineKind||"custom",role:row.querySelector("[data-deadline-final]")?.checked?"finalDraft":"",createdOn:row.dataset.deadlineCreated||todayValue(),name:row.querySelector("[data-deadline-name]").value.trim(),dueDate:row.querySelector("[data-deadline-date]").value,completedOn:row.querySelector("[data-deadline-completed]").value}))}
function renderDeadlineEditor(items=deadlineEditorDraft){deadlineEditorDraft=items;$("#scheduleFields").innerHTML=items.length?items.map((deadline,index)=>`<fieldset class="schedule-field" data-deadline-row="${esc(deadline.id)}" data-deadline-kind="${esc(deadline.kind)}" data-deadline-created="${esc(deadline.createdOn)}"><legend>Step ${index+1}</legend><label>Deadline name<input required data-deadline-name value="${esc(deadline.name)}"></label><label>Due date<input type="date" data-deadline-date value="${esc(deadline.dueDate)}"></label><label>Completed on<input type="date" data-deadline-completed value="${String(deadline.completedOn||"").slice(0,10)}"><small>Leave blank to keep this deadline open.</small></label><div class="deadline-editor-actions"><label class="deadline-role"><input type="radio" name="final-draft-deadline" data-deadline-final ${deadline.role==="finalDraft"?"checked":""}> Final draft gate</label><button type="button" data-deadline-move="up" data-deadline-index="${index}" ${index===0?"disabled":""} aria-label="Move deadline up">↑</button><button type="button" data-deadline-move="down" data-deadline-index="${index}" ${index===items.length-1?"disabled":""} aria-label="Move deadline down">↓</button><button type="button" data-deadline-remove="${index}" aria-label="Remove deadline">Remove</button></div></fieldset>`).join(""):`<div class="empty-deadlines"><strong>No deadlines.</strong><span>Add a deadline to start the production sequence.</span></div>`;$("#scheduleFields").querySelectorAll("[data-deadline-remove]").forEach(button=>button.onclick=()=>{const current=collectDeadlineEditor(),index=Number(button.dataset.deadlineRemove),deadline=current[index];if(deadline.completedOn&&!confirm(`Remove completed deadline “${deadline.name}” and its logged date?`))return;current.splice(index,1);renderDeadlineEditor(current)});$("#scheduleFields").querySelectorAll("[data-deadline-move]").forEach(button=>button.onclick=()=>{const current=collectDeadlineEditor(),from=Number(button.dataset.deadlineIndex),to=button.dataset.deadlineMove==="up"?from-1:from+1;[current[from],current[to]]=[current[to],current[from]];renderDeadlineEditor(current)})}
function openSchedule(){renderDeadlineEditor(structuredClone(state.deadlines));$("#scheduleDialog").showModal()}$("#editScheduleBtn").addEventListener("click",openSchedule);$("#addDeadlineBtn").addEventListener("click",()=>{const current=collectDeadlineEditor();current.push({id:uid(),kind:"custom",role:"",name:"New deadline",dueDate:"",completedOn:"",createdOn:todayValue()});renderDeadlineEditor(current);$("#scheduleFields [data-deadline-row]:last-child [data-deadline-name]")?.select()});document.querySelectorAll(".close-schedule").forEach(b=>b.addEventListener("click",()=>$("#scheduleDialog").close()));$("#scheduleForm").addEventListener("submit",e=>{e.preventDefault();const deadlines=collectDeadlineEditor(),today=localDate(todayValue());if(!deadlines.length)return toast("Keep at least one production deadline");if(deadlines.some(deadline=>!deadline.name))return toast("Every deadline needs a name");if(!deadlines.some(deadline=>deadline.role==="finalDraft"))return toast("Choose one deadline as the final draft gate");let lastDated=null,lastCompleted=null;for(let index=0;index<deadlines.length;index++){const deadline=deadlines[index],due=localDate(deadline.dueDate),completed=localDate(deadline.completedOn);if(completed&&!due)return toast(`Set a due date for “${deadline.name}” before logging completion`);if(due&&lastDated&&due<lastDated)return toast(`Move or redate “${deadline.name}” so deadlines stay in order`);if(due)lastDated=due;if(completed&&completed>today)return toast(`“${deadline.name}” cannot be completed in the future`);if(completed&&deadlines.slice(0,index).some(item=>!item.completedOn))return toast(`Complete earlier steps before “${deadline.name}”`);if(completed&&lastCompleted&&completed<lastCompleted)return toast("Completion dates must follow the deadline order");if(completed)lastCompleted=completed}state.deadlines=deadlines;save();$("#scheduleDialog").close();render();toast("Production deadlines saved")});
$("#pitchBtn").addEventListener("click",()=>openStory());$("#quickPitch").addEventListener("click",()=>openStory());$("#addElementBtn").addEventListener("click",()=>openStory("","","photo"));document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{view=b.dataset.view;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===b));render()}));document.querySelectorAll("[data-workspace-mode]").forEach(b=>b.addEventListener("click",()=>{workspaceMode=b.dataset.workspaceMode;document.body.dataset.workspaceMode=workspaceMode;document.querySelectorAll("[data-workspace-mode]").forEach(x=>x.classList.toggle("active",x===b));if($("#pageDialog").open)$("#pageDialog").close();$(".board-note span:first-child").textContent=workspaceMode==="planning"?"Drag an approved or planned item onto a page to place it.":workspaceMode==="design"?"Select a page to manage its placed items and linked assets.":"Select a page to review its plan, content, assets, and final checklist.";render()}));$("#storyFilters").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{storyFilter=b.dataset.filter;$("#storyFilters").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));renderStories()}));
$("#searchInput").oninput=e=>{search=e.target.value.toLowerCase();renderStories();renderPages()};$("#projectTitle").onblur=e=>{state.title=e.target.textContent.trim()||"Untitled publication";save()};$("#addPagesBtn").onclick=()=>{for(let i=0;i<4;i++){const n=state.pages.length+1;state.pages.push({id:`p${Date.now()}-${i}`,number:n,title:"Untitled page",section:"back",layout:"standard"})}save();render();toast("Four pages added")};$("#removePagesBtn").onclick=()=>{if(state.pages.length<=4)return toast("Keep at least four interior pages");const ids=state.pages.slice(-4).map(x=>x.id);state.stories.forEach(x=>{if(ids.includes(x.pageId))x.pageId=""});state.pages.splice(-4);save();render();toast("Last four pages removed")};
function loadProjectData(payload){
  if(payload?.library?.items?.length){
    library={activeId:payload.library.activeId,items:payload.library.items.map(item=>({...item,data:normalizePublication(item.data)}))};
    const active=library.items.find(item=>item.id===library.activeId&&!item.archived)||library.items.find(item=>!item.archived)||library.items[0];
    library.activeId=active.id;state=active.data;
  }else{
    if(!payload||!Array.isArray(payload.pages)||!Array.isArray(payload.covers)||!Array.isArray(payload.stories))throw new Error("missing publication data");
    state=normalizePublication(payload);const id=uid();library={activeId:id,items:[{id,archived:false,updatedAt:new Date().toISOString(),data:state}]};
  }
  save(false);render();
}
async function openProjectFile(){
  if(!window.flatplanDesktop)return $("#importInput").click();
  try{const result=await window.flatplanDesktop.open();if(result.canceled)return;loadProjectData(result.data);updateFileStatus(result.filePath);toast(`Opened ${result.filePath.split(/[\\/]/).pop()}`)}catch(error){console.error(error);toast("That file is not a valid Flatplan project")}
}
async function saveProjectFile(saveAs=false){
  if(!window.flatplanDesktop){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(workspaceSnapshot(),null,2)],{type:"application/json"}));a.download=`${state.title.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"")||"flatplan"}.flatplan`;a.click();URL.revokeObjectURL(a.href);return}
  try{save(false);setFileStatus("Saving…");await desktopWriteQueue;const result=await (saveAs?window.flatplanDesktop.saveAs(workspaceSnapshot()):window.flatplanDesktop.save(workspaceSnapshot()));if(result.canceled){if(result.filePath)updateFileStatus(result.filePath);return}updateFileStatus(result.filePath);let outputResult=null;try{if(window.getProductionOutputs)outputResult=await window.flatplanDesktop.rewriteProductionOutputs(window.getProductionOutputs())}catch(outputError){console.error(outputError);outputResult={error:true}}if(window.updateProductionOutputStatus)window.updateProductionOutputStatus(outputResult);toast(outputResult?.error?"Project saved; production outputs need attention":outputResult?.directory?"Project and Production Center saved":`Saved ${result.filePath.split(/[\\/]/).pop()}`)}catch(error){console.error(error);setFileStatus("Save failed — choose Save");toast("Flatplan could not save that file")}
}
function acceptOpenedProject(result,message="Opened"){if(!result||result.canceled)return;try{loadProjectData(result.data);updateFileStatus(result.restoreTarget||result.filePath);toast(`${message} ${result.filePath.split(/[\\/]/).pop()}`)}catch(error){console.error(error);toast("That file is not a valid Flatplan project")}}
async function restoreProjectBackup(){try{const result=await window.flatplanDesktop.restoreBackup();if(result?.noBackups)return toast("No project backups are available yet");if(result.canceled)return;acceptOpenedProject(result,"Restored");await saveProjectFile(false)}catch(error){console.error(error);toast("Flatplan could not restore that backup")}}
if($("#resetBtn"))$("#resetBtn").onclick=()=>{if(confirm("Replace this plan with your original imported data?")){state=initial();save();render();toast("Original data restored")}};
if($("#importBtn"))$("#importBtn").onclick=openProjectFile;
$("#importInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{loadProjectData(JSON.parse(await file.text()));updateFileStatus(file.name);toast(`Opened ${file.name}`)}catch{toast("That file is not a valid Flatplan project")}finally{e.target.value=""}};
if($("#exportBtn"))$("#exportBtn").onclick=()=>saveProjectFile(false);
if($("#saveAsBtn"))$("#saveAsBtn").onclick=()=>saveProjectFile(true);
if(window.flatplanDesktop){window.flatplanDesktop.currentPath().then(updateFileStatus);window.flatplanDesktop.startupProject().then(result=>acceptOpenedProject(result,"Reopened"));window.flatplanDesktop.onOpen(openProjectFile);window.flatplanDesktop.onSave(()=>saveProjectFile(false));window.flatplanDesktop.onSaveAs(()=>saveProjectFile(true));window.flatplanDesktop.onRestore(restoreProjectBackup);window.flatplanDesktop.onProjectOpened(result=>acceptOpenedProject(result,"Opened"));setInterval(()=>window.flatplanDesktop.currentPath().then(filePath=>{if(filePath)saveProjectFile(false)}),300000)}else updateFileStatus();
window.addEventListener("focus",renderSchedule);render();
