const productionDialog=document.querySelector("#productionDialog");
let undoStack=[],redoStack=[],restoringHistory=false,lastHistoryState=JSON.stringify(state),assetCheckTimer=0;
const originalSave=save,originalRender=render,originalOpenPage=openPage,originalRenderDeadlineEditor=renderDeadlineEditor,originalCollectDeadlineEditor=collectDeadlineEditor,originalRenderPublicationList=renderPublicationList;

function currentPage(){const id=document.querySelector("#pageId")?.value;return state.pages.find(page=>page.id===id)||state.covers.find(page=>page.id===id)}
function productionOwnerOptions(selected=""){return`<option value="">Unassigned</option>`+state.settings.owners.map(owner=>`<option value="${esc(owner)}" ${owner===selected?"selected":""}>${esc(owner)}</option>`).join("")}
function logActivity(message,kind="change"){state.activity.unshift({id:uid(),at:new Date().toISOString(),message,kind});state.activity=state.activity.slice(0,250)}
function restoreHistory(snapshot,target){restoringHistory=true;target.push(JSON.stringify(state));state=normalizePublication(JSON.parse(snapshot));originalSave();restoringHistory=false;lastHistoryState=JSON.stringify(state);render();toast("Publication history restored")}

save=function(autoSave=true){const current=JSON.stringify(state);if(!restoringHistory&&current!==lastHistoryState){undoStack.push(lastHistoryState);undoStack=undoStack.slice(-50);redoStack=[]}originalSave(autoSave);lastHistoryState=JSON.stringify(state);renderHistoryButtons();renderProductionDashboard();renderActivityLog()};
render=function(){originalRender();renderProductionDashboard();renderLockState();renderActivityLog();scheduleAssetCheck()};

function scheduleAssetCheck(){if(!window.flatplanDesktop)return;clearTimeout(assetCheckTimer);assetCheckTimer=setTimeout(async()=>{let changed=false;for(const page of allProductionPages()){if(!page.assets?.length)continue;const checked=await window.flatplanDesktop.checkAssets(page.assets);if(checked.some((asset,index)=>asset.exists!==page.assets[index]?.exists))changed=true;page.assets=checked}if(changed){originalSave();renderProductionDashboard()}},250)}

function productionStats(){const today=localDate(todayValue()),overdue=state.deadlines.filter(item=>!item.completedOn&&localDate(item.dueDate)&&localDate(item.dueDate)<today),pitched=state.stories.filter(item=>item.status==="pitch"),pageIds=new Set(allProductionPages().map(page=>page.id)),unplaced=state.stories.filter(item=>["planned","approved","complete"].includes(item.status)&&!pageIds.has(item.pageId)),reviews=allProductionPages().filter(page=>!reviewProgress(page).complete),assets=allProductionPages().flatMap(page=>page.assets||[]),missing=assets.filter(asset=>asset.exists===false);return{overdue,pitched,unplaced,reviews,assets,missing}}
function renderProductionDashboard(){const stats=productionStats(),cards=[[stats.overdue.length,"Overdue deadlines","overdue"],[stats.pitched.length,"Unresolved pitches","pitch"],[stats.unplaced.length,"Unplaced content","unplaced"],[stats.reviews.length,"Incomplete reviews","reviews"],[stats.missing.length,"Missing assets","assets"]],markup=cards.map(([count,label,key])=>`<button type="button" data-dashboard="${key}" class="${count?"needs-attention":"clear"}"><strong>${count}</strong><span>${label}</span></button>`).join("");document.querySelector("#productionDashboard").innerHTML=`<div class="dashboard-head"><div><p class="eyebrow">PRODUCTION CONTROL</p><h2>At a glance</h2></div><button class="btn light" type="button" data-open-production>Open production center</button></div><div class="dashboard-grid">${markup}</div>`;const dialogStats=document.querySelector("#productionDialogStats");if(dialogStats)dialogStats.innerHTML=markup;document.querySelector("[data-open-production]").onclick=openProductionCenter;document.querySelectorAll("[data-dashboard]").forEach(button=>button.onclick=()=>openProductionCenter("overview"))}
function renderLockState(){document.body.classList.toggle("publication-locked",state.locked);document.querySelector("#lockPublicationBtn").textContent=state.locked?"Reopen publication":"Lock print-ready edition";document.querySelector("#lockPublicationBtn").disabled=!state.locked&&!getPrintReadiness().ready;["pitchBtn","quickPitch","addElementBtn","addPagesBtn","removePagesBtn","editScheduleBtn","reviewPagesBtn","addSectionBtn","settingsBtn","resetBtn","bulkReviewBtn","bulkShiftBtn"].forEach(id=>{const element=document.getElementById(id);if(element)element.disabled=state.locked});document.querySelector("#projectTitle").contentEditable=state.locked?"false":"true";document.querySelectorAll("#noteForm input,#noteForm button").forEach(element=>element.disabled=state.locked)}
function renderHistoryButtons(){const undo=document.querySelector("#undoBtn"),redo=document.querySelector("#redoBtn");if(undo)undo.disabled=!undoStack.length||state.locked;if(redo)redo.disabled=!redoStack.length||state.locked}
function renderActivityLog(){const root=document.querySelector("#activityLog");if(!root)return;root.innerHTML=state.activity.length?state.activity.map(item=>`<article><time>${new Date(item.at).toLocaleString()}</time><span>${esc(item.message)}</span></article>`).join(""):`<p class="settings-empty">No activity logged yet.</p>`}
function selectProductionTab(name){document.querySelectorAll("[data-production-tab]").forEach(button=>button.classList.toggle("active",button.dataset.productionTab===name));document.querySelectorAll("[data-production-pane]").forEach(pane=>pane.classList.toggle("active",pane.dataset.productionPane===name))}
function openProductionCenter(tab="overview"){renderActivityLog();renderHistoryButtons();renderProductionDashboard();selectProductionTab(tab);if(!productionDialog.open)productionDialog.showModal()}
document.querySelectorAll("[data-production-tab]").forEach(button=>button.onclick=()=>selectProductionTab(button.dataset.productionTab));

if(document.querySelector("#productionBtn"))document.querySelector("#productionBtn").onclick=openProductionCenter;
document.querySelector("main").addEventListener("click",event=>{if(state.locked&&!event.target.closest("[data-open-production]")){event.preventDefault();event.stopImmediatePropagation();toast("This print-ready edition is locked. Reopen it from Production to make changes.")}},true);
document.querySelector("main").addEventListener("dragstart",event=>{if(state.locked){event.preventDefault();toast("Reopen the publication before moving content")}},true);
document.querySelectorAll(".close-production").forEach(button=>button.onclick=()=>productionDialog.close());
document.querySelector("#lockPublicationBtn").onclick=()=>{if(state.locked){if(!confirm("Reopen this print-ready publication for editing? This will be recorded in the activity log."))return;state.locked=false;state.lockedOn="";logActivity("Publication deliberately reopened","reopen");save();render();return}if(!getPrintReadiness().ready)return toast("Complete every print requirement before locking");state.locked=true;state.lockedOn=new Date().toISOString();logActivity("Publication locked as print ready","lock");save();render()};
document.querySelector("#undoBtn").onclick=()=>{if(undoStack.length)restoreHistory(undoStack.pop(),redoStack)};
document.querySelector("#redoBtn").onclick=()=>{if(redoStack.length)restoreHistory(redoStack.pop(),undoStack)};
document.querySelector("#noteForm").onsubmit=event=>{event.preventDefault();const input=document.querySelector("#noteText"),note=input.value.trim();if(!note)return;logActivity(note,"note");input.value="";save();renderActivityLog();toast("Production note added")};

document.querySelector("#duplicatePublicationBtn").onclick=()=>{const title=prompt("Name the duplicated edition",state.title.replace(/\b(19|20)\d{2}\b/,String(new Date().getFullYear()+1))+" Copy");if(!title?.trim())return;const copy=normalizePublication(structuredClone(state));copy.title=title.trim();copy.locked=false;copy.lockedOn="";copy.deadlines.forEach(deadline=>deadline.completedOn="");[...copy.pages,...copy.covers].forEach(page=>page.reviewChecks={});copy.activity=[];const id=uid();library.items.push({id,archived:false,updatedAt:new Date().toISOString(),data:copy});library.activeId=id;state=copy;logActivity(`Edition duplicated from ${state.title}`);save();productionDialog.close();render();toast("New edition created")};
document.querySelector("#bulkReviewBtn").onclick=()=>{if(state.locked)return;const action=confirm("Mark every final-review checklist item complete on every page and cover? Click Cancel to clear all page reviews instead.");allProductionPages().forEach(page=>{page.reviewChecks={};if(action)reviewChecklist().forEach(item=>page.reviewChecks[item.id]=todayValue())});logActivity(action?"All page reviews completed in bulk":"All page reviews cleared in bulk");save();render();toast(action?"All page reviews completed":"All page reviews cleared")};
document.querySelector("#bulkShiftBtn").onclick=()=>{if(state.locked)return;const answer=prompt("Shift every due date by how many days? Use a negative number to move dates earlier.","7"),days=Number(answer);if(answer===null||!Number.isInteger(days))return toast("Enter a whole number of days");state.deadlines.forEach(deadline=>{const date=localDate(deadline.dueDate);if(date){date.setDate(date.getDate()+days);deadline.dueDate=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}});logActivity(`All deadlines shifted ${days} day${Math.abs(days)===1?"":"s"}`);save();render();toast("Deadline dates shifted")};

function templatePublication(type,title){const data=blankPublication(title),counts={"Annual report":24,"Magazine":32,"Newsletter":8}[type]||12;data.template=type.toLowerCase().replace(/\s+/g,"-");data.pages=[];for(let index=0;index<counts;index++)data.pages.push({id:uid(),number:index+1,title:"Untitled page",section:data.sections[Math.min(data.sections.length-1,Math.floor(index/(counts/data.sections.length)))].id,layout:index%6===0?"feature":"standard",reviewChecks:{},assets:[]});return data}
const templateButton=document.createElement("button");templateButton.className="btn light";templateButton.type="button";templateButton.textContent="New from template";document.querySelector("#duplicatePublicationBtn").after(templateButton);templateButton.onclick=()=>{const type=prompt("Template: Annual report, Magazine, Newsletter, or Custom","Annual report");if(!type)return;const matched=["Annual report","Magazine","Newsletter","Custom"].find(item=>item.toLowerCase()===type.trim().toLowerCase());if(!matched)return toast("Choose Annual report, Magazine, Newsletter, or Custom");const title=prompt("Publication name",`New ${matched}`);if(!title?.trim())return;const data=templatePublication(matched,title.trim()),id=uid();library.items.push({id,archived:false,updatedAt:new Date().toISOString(),data});library.activeId=id;state=data;logActivity(`${matched} template created`);save();productionDialog.close();render();toast("Publication created from template")};

function csvCell(value){return`"${String(value??"").replace(/"/g,'""')}"`}
function ownerReportRows(){const names=[...new Set([...state.settings.owners,...state.stories.flatMap(storyOwners)])],groups=[...names.map(name=>({name,items:state.stories.filter(item=>storyOwners(item).includes(name))})),{name:"Unassigned",items:state.stories.filter(item=>!storyOwners(item).length)}];return groups.filter(group=>group.items.length).map(group=>{const active=group.items.filter(item=>item.status!=="denied"),complete=active.filter(item=>item.status==="complete"),outstanding=active.filter(item=>item.status!=="complete"),placedCount=active.filter(item=>item.pageId).length,percent=active.length?Math.round(complete.length/active.length*100):100;return`<tr><td><strong>${esc(group.name)}</strong></td><td>${complete.length}/${active.length} (${percent}%)</td><td>${placedCount}/${active.length}</td><td>${outstanding.map(item=>`${esc(item.title)} <small>(${esc(item.status)}${item.pageId?` · ${esc(labelPage(item.pageId))}`:" · unplaced"})</small>`).join("<br>")||"None"}</td></tr>`}).join("")}
function productionReport(){const stats=productionStats();return`<!doctype html><meta charset="utf-8"><title>${esc(state.title)} production report</title><style>body{font:14px system-ui;max-width:1000px;margin:40px auto;color:#172033}h1,h2{font-family:Georgia}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{border:1px solid #ccd1d8;padding:8px;text-align:left;vertical-align:top}small{color:#667085}.alert{color:#a11}</style><h1>${esc(state.title)}</h1><p>Generated ${new Date().toLocaleString()} · ${state.locked?"Locked print-ready edition":"Working edition"}</p><h2>Production status</h2><p>${stats.overdue.length} overdue · ${stats.pitched.length} unresolved pitches · ${stats.unplaced.length} unplaced · ${stats.reviews.length} incomplete reviews · ${stats.missing.length} missing assets</p><h2>Owner progress</h2><table><tr><th>Owner</th><th>Complete</th><th>Placed</th><th>Outstanding items</th></tr>${ownerReportRows()}</table><h2>Deadlines</h2><table><tr><th>Deadline</th><th>Due</th><th>Completed</th></tr>${state.deadlines.map(item=>`<tr><td>${esc(item.name)}</td><td>${esc(item.dueDate||"—")}</td><td>${esc(item.completedOn||"Open")}</td></tr>`).join("")}</table><h2>Pages</h2><table><tr><th>Page</th><th>Title</th><th>Items</th><th>Review</th><th>Assets</th></tr>${allProductionPages().map(page=>{const progress=reviewProgress(page);return`<tr><td>${esc(labelPage(page.id))}</td><td>${esc(page.title)}</td><td>${placed(page.id).map(item=>`${esc(item.title)} — ${esc(item.status)} — ${esc(storyOwners(item).join(", ")||"Unassigned")}`).join("<br>")||"—"}</td><td>${progress.done}/${progress.total}</td><td>${(page.assets||[]).map(asset=>esc(asset.name)).join(", ")||"—"}</td></tr>`}).join("")}</table>`}
function assignmentsCsv(){const rows=[["Page","Title","Section","Story or element","Type","Status","Owners","Deadline","Due date"]];allProductionPages().forEach(page=>{const items=placed(page.id);(items.length?items:[{}]).forEach((item,index)=>{const deadline=state.deadlines[index]||{};rows.push([labelPage(page.id),page.title,sec(page.section).name,item.title||"",item.type||"",item.status||"",storyOwners(item).join("; "),deadline.name||"",deadline.dueDate||""])})});return rows.map(row=>row.map(csvCell).join(",")).join("\n")}
function preflightReport(){const readiness=getPrintReadiness();return[state.title,"FINAL PREFLIGHT REPORT",`Generated: ${new Date().toLocaleString()}`,`Status: ${readiness.ready?"READY":"NOT READY"}`,"",...readiness.blockers.map(item=>`BLOCKER: ${item}`),"",...allProductionPages().map(page=>{const progress=reviewProgress(page),missing=(page.assets||[]).filter(asset=>asset.exists===false);return`${labelPage(page.id)} — review ${progress.done}/${progress.total}; assets ${(page.assets||[]).length}; missing ${missing.length}`})].join("\n")}
function indesignManifest(){return JSON.stringify({format:"flatplan-indesign-manifest",version:1,publication:state.title,generatedAt:new Date().toISOString(),sections:state.sections,pages:allProductionPages().map(page=>({id:page.id,label:labelPage(page.id),title:page.title,section:sec(page.section).name,layout:page.layout,stories:placed(page.id).map(item=>({id:item.id,title:item.title,type:item.type,owners:storyOwners(item),status:item.status})),assets:(page.assets||[]).map(({name,relativePath,version,modifiedAt,exists})=>({name,relativePath,version,modifiedAt,exists}))}))},null,2)}
function productionOutputs(){const slug=state.title.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"flatplan";return[{kind:"report",name:`${slug}-production-report.html`,content:productionReport(),type:"html"},{kind:"csv",name:`${slug}-assignments.csv`,content:assignmentsCsv(),type:"csv"},{kind:"preflight",name:`${slug}-preflight.txt`,content:preflightReport(),type:"text"},{kind:"manifest",name:`${slug}-indesign-manifest.json`,content:indesignManifest(),type:"json"}]}
window.getProductionOutputs=productionOutputs;
window.updateProductionOutputStatus=result=>{const root=document.querySelector("#productionOutputStatus");if(!root)return;if(result?.error){root.className="output-status error";root.innerHTML="<strong>Project saved, but output files could not be updated.</strong><span>Save again or verify that the project folder is writable.</span>";return}if(!result?.directory)return;root.className="output-status success";root.innerHTML=`<strong>${result.count} output files updated</strong><span>${esc(result.directory)} · ${new Date(result.updatedAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</span>`};
async function exportFile(name,content,type){if(window.flatplanDesktop){const result=await window.flatplanDesktop.exportText({name,content,type});if(!result.canceled)toast(`Exported ${result.filePath.split(/[\\/]/).pop()}`);return}const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([content],{type:"text/plain"}));link.download=name;link.click();URL.revokeObjectURL(link.href)}
document.querySelectorAll("[data-export]").forEach(button=>button.onclick=async()=>{const output=productionOutputs().find(item=>item.kind===button.dataset.export);if(output)return exportFile(output.name,output.content,output.type)});

function assetPreview(asset){const image=/\.(png|jpe?g|gif|svg|webp|tiff?)$/i.test(asset.name),url=asset.path?`file://${asset.path.split("/").map(encodeURIComponent).join("/")}`:"";return image&&asset.exists!==false?`<img src="${url}" alt="">`:`<span>${asset.name.split(".").pop()?.toUpperCase()||"FILE"}</span>`}
async function renderPageAssets(page=currentPage()){const root=document.querySelector("#pageAssetList");if(!root||!page)return;if(window.flatplanDesktop&&page.assets.length){page.assets=await window.flatplanDesktop.checkAssets(page.assets)}root.innerHTML=page.assets.length?page.assets.map((asset,index)=>`<article class="page-asset ${asset.exists===false?"missing":""}">${assetPreview(asset)}<div><strong>${esc(asset.name)}</strong><small>${asset.exists===false?"Missing or moved":esc(asset.relativePath||asset.path)}</small></div><input value="${esc(asset.version||"v1")}" data-asset-version="${index}" aria-label="Version label"><button type="button" data-asset-remove="${index}" aria-label="Remove asset">×</button></article>`).join(""):`<p class="settings-empty">No linked files. Keep originals in the publication's InDesign folder.</p>`;root.querySelectorAll("[data-asset-remove]").forEach(button=>button.onclick=()=>{page.assets.splice(Number(button.dataset.assetRemove),1);logActivity(`Removed an asset link from ${labelPage(page.id)}`);save();renderPageAssets(page)});root.querySelectorAll("[data-asset-version]").forEach(input=>input.onchange=()=>{page.assets[Number(input.dataset.assetVersion)].version=input.value.trim()||"v1";save()})}
function renderReviewInventory(page){const items=placed(page.id),assets=page.assets||[],planReady=Boolean(page.title&&page.layout&&(!page.number||page.section)),rows=[{label:"Page plan",detail:planReady?`${page.title} · ${page.layout}`:"Page title, section, or layout needs attention",ready:planReady},...items.map(item=>({label:item.title,detail:`${item.type} · ${item.status}${storyOwners(item).length?` · ${storyOwners(item).join(", ")}`:" · unassigned"}`,ready:item.status==="complete",itemId:item.id})),...assets.map(asset=>({label:asset.name,detail:`Asset · ${asset.version||"No version label"}${asset.exists===false?" · missing":""}`,ready:asset.exists!==false}))];const root=document.querySelector("#reviewInventory");root.innerHTML=`<div class="page-review-head"><div><p class="field-label">Page contents</p><small>Every element should be complete and every linked asset available.</small></div><strong class="${rows.every(row=>row.ready)?"complete":""}">${rows.filter(row=>row.ready).length} / ${rows.length}</strong></div><div class="review-inventory-list">${rows.length?rows.map(row=>`<div class="review-inventory-row ${row.ready?"complete":"attention"}"><span class="review-state">${row.ready?"✓":"!"}</span><div><strong>${esc(row.label)}</strong><small>${esc(row.detail)}</small></div>${row.itemId?`<button class="btn light" type="button" data-review-edit-item="${row.itemId}">Edit</button>`:""}</div>`).join(""):`<p class="settings-empty">No content or assets are assigned to this page.</p>`}</div>`;root.querySelectorAll("[data-review-edit-item]").forEach(button=>button.onclick=()=>{document.querySelector("#pageDialog").close();openStory(button.dataset.reviewEditItem)})}
openPage=function(id){originalOpenPage(id);const page=currentPage();document.querySelectorAll(".page-card").forEach(card=>card.classList.toggle("selected",card.dataset.page===id));renderPageAssets(page);renderReviewInventory(page);document.querySelector("#pageForm .dialog-actions .btn.dark").textContent=workspaceMode==="review"?"Save review":"Save page";document.querySelectorAll("#pageReviewChecklist .review-check").forEach((label,index)=>{const owner=reviewChecklist()[index]?.owner;if(owner){const badge=document.createElement("small");badge.textContent=`Assigned to ${owner}`;label.append(badge)}})};
const pageMoveControls=document.createElement("section");pageMoveControls.className="page-move-controls";pageMoveControls.innerHTML=`<p class="field-label">Page order</p><div><button class="btn light" type="button" id="movePageEarlier">← Move earlier</button><button class="btn light" type="button" id="movePageLater">Move later →</button></div>`;document.querySelector(".page-assets").before(pageMoveControls);
function moveCurrentPage(offset){if(state.locked)return;const page=currentPage(),index=state.pages.findIndex(item=>item.id===page?.id),target=index+offset;if(index<0||target<0||target>=state.pages.length)return;[state.pages[index],state.pages[target]]=[state.pages[target],state.pages[index]];state.pages.forEach((item,pageIndex)=>item.number=pageIndex+1);logActivity(`${page.title||`Page ${target+1}`} moved to page ${target+1}`);save();render();openPage(page.id);toast(`Page moved to position ${target+1}`)}
document.querySelector("#movePageEarlier").onclick=()=>moveCurrentPage(-1);document.querySelector("#movePageLater").onclick=()=>moveCurrentPage(1);
const pageMoveOpenPage=openPage;openPage=function(id){pageMoveOpenPage(id);const index=state.pages.findIndex(item=>item.id===id),isInterior=index>=0;pageMoveControls.hidden=!isInterior;document.querySelector("#movePageEarlier").disabled=!isInterior||index===0||state.locked;document.querySelector("#movePageLater").disabled=!isInterior||index===state.pages.length-1||state.locked};
document.querySelector("#linkAssetsBtn").onclick=async()=>{if(state.locked)return;if(!window.flatplanDesktop)return toast("Asset linking is available in the Mac app");const result=await window.flatplanDesktop.selectAssets();if(result.canceled)return;const page=currentPage();const known=new Set(page.assets.map(asset=>asset.path));result.files.filter(file=>!known.has(file.path)).forEach(file=>page.assets.push({...file,id:uid()}));logActivity(`Linked ${result.files.length} asset${result.files.length===1?"":"s"} to ${labelPage(page.id)}`);save();renderPageAssets(page)};

renderDeadlineEditor=function(items=deadlineEditorDraft){originalRenderDeadlineEditor(items);document.querySelectorAll("[data-deadline-row]").forEach((row,index)=>{const deadline=items[index],label=document.createElement("label");label.innerHTML=`Assigned to<select data-deadline-owner>${productionOwnerOptions(deadline.owner)}</select>`;row.insertBefore(label,row.querySelector(".deadline-editor-actions"))})};
collectDeadlineEditor=function(){const values=originalCollectDeadlineEditor();document.querySelectorAll("[data-deadline-row]").forEach((row,index)=>values[index].owner=row.querySelector("[data-deadline-owner]")?.value||"");return values};

renderPublicationList=function(){originalRenderPublicationList();filterPublicationList()};
const archiveSearch=document.createElement("input");archiveSearch.id="archiveSearch";archiveSearch.placeholder="Search current and archived publications";archiveSearch.className="archive-search";document.querySelector("#publicationList").before(archiveSearch);archiveSearch.oninput=filterPublicationList;
function filterPublicationList(){const query=archiveSearch.value.toLocaleLowerCase();document.querySelectorAll("#publicationList .publication-row").forEach((row,index)=>{const item=[...library.items].sort((a,b)=>(a.archived-b.archived)||String(b.updatedAt).localeCompare(String(a.updatedAt)))[index];const haystack=`${item?.data?.title||""} ${(item?.data?.stories||[]).map(story=>`${story.title} ${storyOwners(story).join(" ")}`).join(" ")}`.toLocaleLowerCase();row.hidden=Boolean(query&&!haystack.includes(query))})}

document.addEventListener("keydown",event=>{if(!(event.metaKey||event.ctrlKey))return;if(event.target.matches("input,textarea,select,[contenteditable=true]"))return;if(event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?document.querySelector("#redoBtn").click():document.querySelector("#undoBtn").click()}if(event.key.toLowerCase()==="p"&&event.shiftKey){event.preventDefault();openProductionCenter()}});
async function sendDeadlineReminder(){const today=todayValue(),key=`flatplan-reminder-${today}`;if(localStorage.getItem(key)||!window.flatplanDesktop)return;const due=state.deadlines.filter(item=>!item.completedOn&&localDate(item.dueDate)&&Math.ceil((localDate(item.dueDate)-localDate(today))/86400000)<=3);if(!due.length)return;localStorage.setItem(key,"1");const overdue=due.filter(item=>localDate(item.dueDate)<localDate(today)).length;await window.flatplanDesktop.notify(`${state.title} production reminder`,overdue?`${overdue} deadline${overdue===1?" is":"s are"} overdue.`:`${due.length} deadline${due.length===1?" is":"s are"} due within three days.`)}

normalizePublication(state);lastHistoryState=JSON.stringify(state);render();sendDeadlineReminder();
